name: Deploy SF Metadata PR 🔄
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:  
  setup-environment:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.process-branch.outputs.target }}
    steps:
      - name: Extract and Uppercase Environment
        id: process-branch
        run: |
          # Get the branch name (e.g., release/staging)
          echo ${{ github.event.pull_request.base.ref || github.ref_name }}
          FULL_BRANCH="${{ github.event.pull_request.base.ref || github.ref_name }}"          
          # 1. Extract the part after 'release/'
          # 2. Convert to uppercase using 'tr'
          ENV_NAME=$(echo "${FULL_BRANCH}" | sed 's/^release[-/]//g' | tr  '[:upper:]' '[:lower:]')
          echo $ENV_NAME
          echo "target=$ENV_NAME" >> $GITHUB_OUTPUT
  DeployMetadata:
    needs: setup-environment
    if: |
      github.event.pull_request.merged == true || 
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: ${{ needs.setup-environment.outputs.env_name }}
    container: manu2pace/2pacerunner:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: git delta
        shell: bash
        run: |          
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
          echo "##[section] Branch Name: $BRANCH_NAME"
          echo "##[section]Looking for metadata changes..."
          mkdir sgdPackage
          sf sgd source delta --to "HEAD" --from deploy${{ needs.setup-environment.outputs.env_name }} -d --output-dir sgdPackage/
      - name: Deploy Metadata
        env:
          ORG_ALIAS: ${{ needs.setup-environment.outputs.env_name }}
          GH_TOKEN: ${{ secrets.CI_PAT }}

        run: |

          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}

          echo "##[section] Branch Name: $BRANCH_NAME"

          echo "##[section] Setting connexion org alias ${{ env.ORG_NAME }} "
          echo ${{ secrets.SFDXAUTHURL }} > ./SFDX_URL.txt
          echo "##[section]Defining target org for branch $BRANCH_NAME..."

          echo "##[command]sf org login sfdx-url --sfdx-url-file ./SFDX_URL.txt -a target_org --set-default"
          sf org login sfdx-url --sfdx-url-file ./SFDX_URL.txt -a target_org --set-default

          echo "##[section]Package contents:"

          if [ -d "sgdPackage/force-app" ]; then
              SGD_SOURCE1="-d sgdPackage/force-app"
              find sgdPackage/force-app | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
          fi

          echo " "
          echo " "

          if [ -f test-classes.txt ]; then
              echo "##[section]Building test class list..."
              SF_RUNTESTS=`tr -s '\n' ' ' < test-classes.txt | sed 's/,$//'`
              if [ -n "$SF_RUNTESTS" ]; then
                echo "##[section]Tests to run: $SF_RUNTESTS"
                TEST_CMD="-l RunSpecifiedTests -tests $SF_RUNTESTS"
              else
                TEST_CMD="-l RunRelevantTests"
                echo "##[command] RunRelevantTests."
              fi
          fi

          echo " "
          echo " "

          if [ -d "sgdPackage/force-app" ]; then
            echo "##[section]---Validate to target_org...---"

            echo "##[command]sf project deploy start -c $SGD_SOURCE1 $SGD_SOURCE2 -o target_org $TEST_CMD --json"
            JOB_RESULT=$(sf project deploy start -c $SGD_SOURCE1 $SGD_SOURCE2 -o target_org $TEST_CMD --json) 
                    echo "##[section]---Deploy to target_org...---"

            JOB_ID=$(echo $JOB_RESULT | jq -r .result.id)
            JOB_STATUS=$(echo $JOB_RESULT | jq -r .result.status)

            echo "##[command]JOB_ID: $JOB_ID"
            echo "##[command]JOB_STATUS: $JOB_STATUS"

            if [ "$JOB_STATUS" != "Succeeded" ]; then
              echo "##[error]Deploy to target_org failed with status $JOB_STATUS."
              exit 1
            fi
            # Push the specific tag to remote to HEAD
            git tag -f "release${ORG_ALIAS}" HEAD
            git push origin "release${ORG_ALIAS}" --force

          fi
